platform :ios, '13.0'
use_frameworks! :linkage => :static

target 'SwiftCollectionsExample' do
  pod 'SuperCollections', :git => 'https://github.com/CloudlessMoon/swift-collections-cocoapods.git'
end
